disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - type_body_length
  - function_body_length
  - force_cast

identifier_name:
  excluded: # excluded via string array
    - _annotationData
    - id
    - URL
    - lm
    - km
    - x
    - y
    - aq
